"""
State multiplicity of the tetrahedral and octahedral cages.

The tetrahedral defect of Ref. [KulkarniMatter] carries a four-state charge
multiplet, generated by assigning an independent winding number to each of
three mutually equivalent valence bonds after one bond is selected as the
anchor. This script checks whether the same construction can run on the
octahedral cage.

It computes, for each cage:

  * the point group order;
  * the stabilizer of a single bond direction, and its orbits on the
    remaining bonds;
  * the projections of the remaining bonds onto the selected bond;
  * whether the inversion operator is present.

The result is that anchor selection on the tetrahedron leaves three
equivalent valence bonds, while on the octahedron it leaves two
inequivalent classes. The octahedral cage therefore supports no winding
ladder and no charge multiplet.

Requires numpy only. Runs in about two seconds.
"""
from itertools import permutations
import numpy as np

TOL = 1e-9

TET = [(1, 1, 1), (1, -1, -1), (-1, 1, -1), (-1, -1, 1)]
OCT = [(1, 0, 0), (-1, 0, 0), (0, 1, 0), (0, -1, 0), (0, 0, 1), (0, 0, -1)]


def point_group(vertices):
    """Every orthogonal map that permutes the vertex set."""
    V = np.array(vertices, dtype=float)
    ops = []
    for perm in permutations(range(len(V))):
        target = V[list(perm)]
        M, *_ = np.linalg.lstsq(V, target, rcond=None)
        if not np.allclose(V @ M, target, atol=TOL):
            continue
        if not np.allclose(M.T @ M, np.eye(3), atol=TOL):
            continue
        ops.append((perm, M))
    return ops


def stabilizer_orbits(ops, fixed, n):
    """Orbits of the stabilizer of one vertex on the remaining vertices."""
    stab = [perm for perm, _ in ops if perm[fixed] == fixed]
    seen = set()
    for v in range(n):
        if v == fixed:
            continue
        seen.add(frozenset(perm[v] for perm in stab))
    return stab, sorted((len(o) for o in seen), reverse=True)


def report(name, vertices):
    V = np.array(vertices, dtype=float)
    U = V / np.linalg.norm(V, axis=1)[:, None]
    ops = point_group(vertices)
    stab, orbits = stabilizer_orbits(ops, 0, len(V))
    proj = sorted(round(float(U[0] @ U[i]), 6) for i in range(1, len(V)))
    has_inv = any(np.allclose(M, -np.eye(3), atol=TOL) for _, M in ops)

    print(f"\n{name}")
    print(f"    point group order                  {len(ops)}")
    print(f"    stabilizer of one bond, order      {len(stab)}")
    print(f"    its orbits on the remaining bonds  {orbits}")
    print(f"    projections onto the chosen bond   {proj}")
    print(f"    sum of all projections             "
          f"{1 + sum(proj):.6f}   (charge conservation)")
    print(f"    inversion -I present               {has_inv}")
    return orbits, proj, has_inv


print("Bond structure after anchor selection")
print("=" * 60)
orb_t, proj_t, inv_t = report("Tetrahedral cage K_4", TET)
orb_o, proj_o, inv_o = report("Octahedral cage K_{2,2,2}", OCT)

assert orb_t == [3] and np.allclose(proj_t, [-1 / 3] * 3) and not inv_t
assert orb_o == [4, 1] and np.allclose(proj_o, [-1, 0, 0, 0, 0]) and inv_o

print("\n" + "=" * 60)
print("Tetrahedron: one orbit of size 3. The three valence bonds are")
print("  mutually equivalent and share the projection -1/3, so each may")
print("  carry an independent winding number. Total winding W in {0,1,2,3}")
print("  gives four charge states. Inversion is absent, so the two void")
print("  orientations give matter and antimatter separately.")
print("\nOctahedron: two orbits, of sizes 4 and 1. The remaining bonds are")
print("  not mutually equivalent, and their projections are -1 and 0.")
print("  There is no set of equivalent valence bonds to carry independent")
print("  windings, so no charge ladder forms. Inversion is present, so the")
print("  cage is its own image and there is no partner orientation.")
print("\nGeometric state multiplicity:  tetrahedral 4 x 2 = 8,  octahedral 1")
